apiVersion: v1
kind: Pod
metadata:
  name: singlecontainer-pod
spec:
  containers:
  - name: producer
    image: ubuntu
    command: ["/bin/bash"]
    args: ["-c", "echo $(hostname) $(date) >> /var/log/index.html"]
    volumeMounts:
    - name: webcontent
      mountPath: /var/log
  volumes:
  - name: webcontent 
    emptyDir: {}
